<?php

namespace App\Exceptions;

use AElnemr\RestFullResponse\CoreJsonResponse;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Throwable;

class Handler extends ExceptionHandler
{
    use CoreJsonResponse;

    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {

        if ($e instanceof ValidationException && $request->isJson()) {
            return $this->invalidRequest($e->errors());
        }

        if ($e instanceof HttpException && $request->isJson()) {

            if ($e->getStatusCode() == 401) {
                return $this->unauthorized();
            }
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
